app.urlstub=http://localhost:8080/QuinCe
email.starttls=true
email.ssl=false
email.hostname=smtp.fastmail.com
email.port=587
email.username=steve@squaregoldfish.co.uk
email.password=9s5u4b5s6a8d6v93
email.fromname=QuinCe
email.fromaddress=quince@quince.science
filestore=/home/steve.jones@vliz.be/quince_files/FILESTORE.380
qc_routines.configfile=/home/steve.jones@vliz.be/Documents/QuinCe/QuinCe/configuration/qc_routines_config.csv
externalstandards_routines.configfile=/home/steve.jones@vliz.be/Documents/QuinCe/QuinCe/configuration/externalstandards_routines_config.csv
data_reduction_qc_routines.configfile=/home/steve.jones@vliz.be/Documents/QuinCe/QuinCe/configuration/data_reduction_qc_config.json
export.configfile=/home/steve.jones@vliz.be/Documents/QuinCe/QuinCe/configuration/export_config.json
map.max_points=1000
diagnostic_sensors=Temperature,Pressure,Air Flow,Water Flow,Voltage
version=v25.0.0
instance_credits=Steve Jones, VLIZ;André Bjärby, ICOS Carbon Portal/Lund University, Sweden
instance_host=VLIZ
submission_enabled=true
